version: "3.8"
services:
    interbtc:
        image: "interlayhq/interbtc:1.25.0-rc4"
        command:
            - --rpc-external
            - --ws-external
            - --rpc-methods=unsafe
            - --dev
            - --instant-seal
        ports:
            - "9933:9933"
            - "9944:9944"
    bitcoind:
        image: "ruimarinho/bitcoin-core:22"
        command:
            - -regtest
            - -server
            - -rpcbind=0.0.0.0
            - -rpcallowip=0.0.0.0/0
            - -rpcuser=rpcuser
            - -rpcpassword=rpcpassword
            - -fallbackfee=0.0002
        ports:
            - "18443:18443"
    bitcoin-cli:
        image: "ruimarinho/bitcoin-core:22"
        command:
            - /bin/sh
            - -c
            - |
                bitcoin-cli -regtest -rpcconnect=bitcoind -rpcwait -rpcuser=rpcuser -rpcpassword=rpcpassword createwallet Alice
                ALICE_ADDRESS=$$(bitcoin-cli -regtest -rpcconnect=bitcoind -rpcwait -rpcuser=rpcuser -rpcpassword=rpcpassword -rpcwallet=Alice getnewaddress)
                # coins need 100 confirmations to be spendable
                bitcoin-cli -regtest -rpcconnect=bitcoind -rpcwait -rpcuser=rpcuser -rpcpassword=rpcpassword generatetoaddress 101 $${ALICE_ADDRESS}
    electrs:
        image: "interlayhq/electrs:latest"
        command:
            - electrs
            - -vvvv
            - --network
            - regtest
            - --jsonrpc-import
            - --cors
            - "*"
            - --cookie
            - "rpcuser:rpcpassword"
            - --daemon-rpc-addr
            - "bitcoind:18443"
            - --http-addr
            - "[::0]:3002"
            - --index-unspendables
        ports:
            - "3002:3002"
        restart: always
