version: "3.8"
services:
    bitcoind:
        image: "ruimarinho/bitcoin-core:0.20"
        command:
            - -testnet
            - -server
            - -prune=550
            - -par=1
            - -maxuploadtarget=200
            - -blocksonly
            - -rpcbind=0.0.0.0
            - -rpcallowip=0.0.0.0/0
            - -rpcuser=rpcuser
            - -rpcpassword=rpcpassword
            - -fallbackfee=0.0002
        ports:
            - "18332:18332"
        volumes:
            - ./cache:/home/bitcoin/.bitcoin/testnet3
    vault:
        image: "registry.gitlab.com/interlay/polkabtc-clients/vault:0.5.0"
        command:
            - /bin/sh
            - -c
            - |
                echo "Sleeping..."
                sleep 10
                vault \
                    --http-addr '[::0]:3032' \
                    --bitcoin-rpc-url http://bitcoind:18332 \
                    --bitcoin-rpc-user rpcuser \
                    --bitcoin-rpc-pass rpcpassword \
                    --network=testnet \
                    --keyfile /keyfile.json \
                    --keyname polkabtcvault \
                    --auto-register-with-faucet-url 'https://beta.polkabtc.io/api/faucet' \
                    --polka-btc-url 'wss://beta.polkabtc.io/api/parachain'
        ports:
            - "3032:3032"
        volumes:
            - type: bind
              source: ./keyfile.json
              target: /keyfile.json